project:
  type: book
  output-dir: docs

book:
  title: "Analyse économétrique de données spatiales pour évaluer l'impact de politiques et projets"
  author: "Florent Bédécarrats, Marc Bouvier, Kenneth Houngbedji, Jeanne de Montalembert et Marin Ferry"
  date: "10/3/2022"
  repo-url: https://github.com/fBedecarrats/spatial-impact-evaluation
  cover-image: figs/IRD_010664_ORI_small.png
  cover-image-alt: Déforestation à Madagascar © IRD - Bernard Moizo
  chapters:
    - index.qmd
    - 00-intro.qmd
    - part: "Fondamentaux"
      chapters: 
        - 00-theorie.qmd
    - part: "Préparation des données"
      chapters: 
        - 01-aires_protegees.qmd
        - 02-caracteristiques_AP.qmd
        - 03-donnees_deforestation.qmd
        - 04-donnees_en_mailles.qmd
        - 04b-recap_donnees_dispo.qmd
    - part: "Évaluation d'impact"
      chapters: 
        - 05-assignation_aleatoire.qmd
        - 06-matching_AP.qmd
        - 06b-matching_mailles.qmd
        - 07-avant_apres.qmd
        - 08-diff_in_diff.qmd
    - part: "Ressources"
      chapters:
        - 09-bibliographie.qmd
        - 10-fondamentaux_R.qmd
    

bibliography: bibliographie.bib

format:
  html:
    theme: cosmo
    code-fold: true

execute:
  warning: false
  error: false
